spring:
  profiles:
    group:
      correct: "test2,test1"
---
spring:
  config:
    activate:
      on-profile: "test1"
  datasource:
    username: "proddbuser1"
    password: "proddbpass1"
---
spring:
  config:
    activate:
      on-profile: "test2"
  datasource:
    username: "proddbuser2"
    password: "proddbpass2"
