spring:
  config:
    activate:
      on-profile: "correct"
  profiles:
    group:
      correct: "test1,test2"
  datasource:
    username: "proddbuser"
    password: "proddbpass"      
---
spring:
  config:
    activate:
      on-profile: "test1"
  datasource:
    username: "proddbuser1"
    password: "proddbpass1"
---
spring:
  config:
    activate:
      on-profile: "test2"
  datasource:
    username: "proddbuser2"
    password: "proddbpass2"
