spring:
  config:
    activate:
      on-profile: "correct"
  profiles:
    group:
      "correct": "test1,test2"
test: "aaaa"
---
spring:
  config:
    activate:
      on-profile: "test1"
test: "bbbb"
---
spring:
  config:
    activate:
      on-profile: "test1"
test: "cccc"

