spring:
  profiles:
    include: "local"
---
spring.profiles: "local"
spring.profiles.include: "test1,test2"
test: "aaaa"
---
spring:
  profiles: "test1"
test: "bbbb"
---
spring:
  profiles: "test2"
test: "cccc"

