spring:
  profiles:
    active: "local"
---
spring:
  profiles: "local"
    include: "test1,test2"
test: "aaaa"
---
spring:
  profiles: "test1"
test: "bbbb"
---
spring:
  profiles: "test2"
test: "cccc"

